# Generated by Django 4.0.5 on 2022-06-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
