# Generated by Django 4.0.5 on 2022-06-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_rename_user_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
